name: "🐞 버그 리포트"
description: "버그 발생에 관한 이슈를 생성합니다."
title: "[Bug]: "
labels: ["Fix"]
assignees:
  - bumsu01
body:
  - type: markdown
    attributes:
      value: "버그를 찾아주셔서 감사합니다!"
  - type: markdown
    attributes:
      value: |
        - 이슈를 등록하기 전에, [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)를 읽어주시기 바랍니다. 당신이 놓친 부분으로 인해 발생한 버그일 가능성이 있습니다!
        - 이슈를 등록하기 전에, 이미 등록된 이슈인지 [REPORTED](https://github.com/bumsu01/bumsu01.github.io/issues)에서 확인해주세요.
        - 코드에 궁금한 점이 있을 경우에는 [BLOG](https://bbmsk2.tistory.com/) 를 이용해주세요.
  - type: input
    id: contact
    attributes:
      label: 연락처 정보
      description: 추가 정보가 필요한 경우 연락할 정보를 부탁드립니다.
      placeholder: ex. bumsu01@gmail.co.kr
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 현상 설명 (사진이나 코드를 이용하면 이해하는데 도움이 됩니다.)
      description: 어떤 현상이 발생하는지 Given-When-Then 형식으로 상세하게 작성해 주세요.
      placeholder: Tell us what you see!
      value: "Given\n- [...]\nWhen\n- [...]\nThen\n- [...]"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 현재 실행 중인 SONA 버전은 무엇입니까?
      options:
        - 0.1.0 (Default)
        - 1.0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: 어떤 환경에서 문제가 발생하나요?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - IOS
        - Android
  - type: textarea
    id: logs
    attributes:
      label: 관련 로그 출력
      description: 관련 로그 출력을 복사하여 붙여넣으세요.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: 문서 확인은 하셨나요?
      description: 이 이슈를 제출하기 전에 모든 문서를 읽어보고도 edge case가 있었습니까? [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)
      options:
        - label: 나는 이 프로젝트의 모든 문서를 읽었습니다
          required: true
