name: "✨ 기능 추가"
description: "기능 추가에 대한 이슈를 생성합니다."
title: "[Feature]: "
labels: ["Feature"]
assignees:
  - bumsu01
body:
  - type: markdown
    attributes:
      value: "기능 추가 아이디어를 제시해주셔서 감사합니다!"
  - type: markdown
    attributes:
      value: |
        - 이슈를 등록하기 전에, [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)를 읽어주시기 바랍니다. 당신이 놓친 부분으로 인해 발생한 버그일 가능성이 있습니다!
        - 이슈를 등록하기 전에, 이미 등록된 이슈인지 [REPORTED](https://github.com/bumsu01/bumsu01.github.io/issues)에서 확인해주세요.
        - 코드에 궁금한 점이 있을 경우에는 [BLOG](https://bbmsk2.tistory.com/) 를 이용해주세요.
  - type: input
    id: contact
    attributes:
      label: 연락처 정보
      description: 추가 정보가 필요한 경우 연락할 정보를 부탁드립니다.
      placeholder: ex. bumsu01@gmail.co.kr
    validations:
      required: false
  - type: textarea
    id: what-feature
    attributes:
      label: 어떤 기능인가요?
      description: 추가하려는 기능에 대해 간결하게 설명해주세요
      placeholder: 원하는 기능에 대한 명확하고 간결한 설명을 작성해주세요!
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 제안할 솔루션
      description: 고려한 대체 솔루션이나 기능에 대한 명확한 설명을 작성해주세요.
      render: shell
  - type: textarea
    id: feature-with-bug
    attributes:
      label: 버그와 관련 있는 이슈인가요?
      description: 기능 요청이 문제와 관련되어 있습니까? 설명해주세요.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: 문서 확인은 하셨나요?
      description: 이 이슈를 제출하기 전에 모든 문서를 읽어보고도 edge case가 있었습니까? [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)
      options:
        - label: 나는 이 프로젝트의 모든 문서를 읽었습니다
          required: true
