name: "📓 문서 수정 리포트"
description: "문서 수정에 관한 이슈를 생성합니다."
title: "[Documentation]: "
labels: ["Docs"]
assignees:
  - bumsu01
body:
  - type: markdown
    attributes:
      value: "잘못된 문서를 찾아주셔서 감사합니다!"
  - type: markdown
    attributes:
      value: |
        - 이슈를 등록하기 전에, [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)를 읽어주시기 바랍니다. 당신이 놓친 부분으로 인해 발생한 버그일 가능성이 있습니다!
        - 이슈를 등록하기 전에, 이미 등록된 이슈인지 [REPORTED](https://github.com/bumsu01/bumsu01.github.io/issues)에서 확인해주세요.
        - 코드에 궁금한 점이 있을 경우에는 [BLOG](https://bbmsk2.tistory.com/) 를 이용해주세요.
  - type: input
    id: contact
    attributes:
      label: 연락처 정보
      description: 추가 정보가 필요한 경우 연락할 정보를 부탁드립니다.
      placeholder: ex. bumsu01@gmail.co.kr
    validations:
      required: false
  - type: textarea
    id: what-document
    attributes:
      label: 수정해야할 문서
      description: 여기에 수정할 문서 대한 다른 컨텍스트나 스크린샷을 추가하세요.
      placeholder: 수정해야할 곳을 보여주세요!
      value: "링크(url)의 포스터에 들어있는 A 내용이 잘못되었습니다. [...] 이렇게 수정해야합니다."
    validations:
      required: true
  - type: textarea
    id: document-modify-text
    attributes:
      label: 추가를 원하는 내용
      description: 추가했으면 하는 포스트가 있다면 섹션/콘텐츠에 나열하세요.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: 문서 확인은 하셨나요?
      description: 이 이슈를 제출하기 전에 모든 문서를 읽어보고도 edge case가 있었습니까? [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)
      options:
        - label: 나는 이 프로젝트의 모든 문서를 읽었습니다
          required: true
