name: "🛃 커스텀 이슈"
description: "커스텀 이슈"
title: "[Issue]: "
labels: [""]
assignees:
  - bumsu01
body:
  - type: markdown
    attributes:
      value: "create issue template!"
  - type: markdown
    attributes:
      value: |
        - 이슈를 등록하기 전에, [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)를 읽어주시기 바랍니다. 당신이 놓친 부분으로 인해 발생한 버그일 가능성이 있습니다!
        - 이슈를 등록하기 전에, 이미 등록된 이슈인지 [REPORTED](https://github.com/bumsu01/bumsu01.github.io/issues)에서 확인해주세요.
        - 코드에 궁금한 점이 있을 경우에는 [BLOG](https://bbmsk2.tistory.com/) 를 이용해주세요.
  - type: input
    id: contact
    attributes:
      label: 연락처 정보
      description: 추가 정보가 필요한 경우 연락할 정보를 부탁드립니다.
      placeholder: ex. bumsu01@gmail.co.kr
    validations:
      required: false
  - type: textarea
    id: what-issue
    attributes:
      label: 현상 설명 (사진이나 코드를 이용하면 이해하는데 도움이 됩니다.)
      description: 어떤 현상이 발생하는지 Given-When-Then 형식으로 상세하게 작성해 주세요.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 문서 확인은 하셨나요?
      description: 이 이슈를 제출하기 전에 모든 문서를 읽어보고도 edge case가 있었습니까? [README](https://github.com/bumsu01/bumsu01.github.io/blob/main/README.md)
      options:
        - label: 나는 이 프로젝트의 모든 문서를 읽었습니다
          required: true
