import type { Metadata } from "next";
import RootLayout from "./layout";
import HomePage from "./home/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      App Page - {process.env.NEXT_PUBLIC_WEB_DOMAIN as string}
      <br />
      <HomePage />
    </div>
  );
}
